### ISSUE TITLE
automatic crash reporting does not seem to work

### ISSUE THREAD

**Issue by duksis** [ForzaElixir/rollbax#124]
have configured rollbax as follows in `config/prod.exs`

```yaml
config :rollbax,
   enable_crash_reports: true,
   enabled: true,
   access_token: "xxxxxxxxxxxxxxxxxxxxxxx",
   environment: "staging"
``` 

but no exceptions are being reported automatically

manual reporting does end up in my rollbar account

```elixir
try do
  DoesNotExist.for_sure()
rescue
  exception ->
    Rollbax.report(:error, exception, System.stacktrace())
end
```
^ This works, but automatic crash reporting does not
appreciate any hints on what I might be doing wrong.
